development:
  adapter: mysql2
  database: posts_dev
  hostname: localhost
  username: root
  password: root 
  pool: 5
test:
  adapter: mysql2
  database: posts_test
  hostname: localhost
  username: root
  password: root 
  pool: 5  